# List of URLs
links = ['https://docs.snowflake.com/en/user-guide/data-time-travel.html#changing-the-data-retention-period-for-an-object',
 'https://docs.snowflake.com/en/sql-reference/sql/explain.html',
 'https://docs.snowflake.com/en/sql-reference/constructs/sample.html',
 'https://docs.snowflake.com/en/user-guide/ui-snowsight-query.html#creating-custom-filters',
 'https://docs.snowflake.com/en/user-guide/views-secure.html#how-might-data-be-exposed-by-a-non-secure-view',
 'https://community.snowflake.com/s/article/Performance-impact-from-local-and-remote-disk-spilling',
 'https://docs.snowflake.com/en/user-guide/data-load-overview.html#detection-of-column-definitions-in-staged-semi-structured-data-files',
 'https://docs.snowflake.com/en/sql-reference/functions/ntile.html',
 'https://docs.snowflake.com/en/user-guide/tables-external-intro.html#general-file-sizing-recommendations',
 'https://docs.snowflake.com/en/sql-reference/functions/flatten.html#output',
 'https://docs.snowflake.com/en/sql-reference/sql/create-table.html#create-table-using-template',
 'https://docs.snowflake.com/en/sql-reference/functions/row_number.html',
 'https://docs.snowflake.com/en/user-guide/views-materialized.html',
 'https://docs.snowflake.com/en/sql-reference/functions/sha2.html',
 'https://docs.snowflake.com/en/sql-reference/data-types-numeric.html#float-float4-float8',
 'https://docs.snowflake.com/en/user-guide/querying-approximate-cardinality.html',
 'https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html#using-values-in-a-variant',
 'https://docs.snowflake.com/en/sql-reference/sql/put.html',
 'https://docs.snowflake.com/en/sql-reference/functions/to_timestamp.html',
 'https://docs.snowflake.com/en/user-guide/ui-query-profile.html#queries-too-large-to-fit-in-memory',
 'https://docs.snowflake.com/en/sql-reference/constructs/pivot.html',
 'https://docs.snowflake.com/en/sql-reference/functions/approx_count_distinct.html',
 'https://docs.snowflake.com/en/user-guide/ui-snowsight-query.html#automatic-contextual-statistics',
 'https://docs.snowflake.com/en/user-guide/data-load-considerations-prepare.html#file-sizing-best-practices-and-limitations',
 'https://docs.snowflake.com/en/sql-reference/functions/datediff.html',
 'https://docs.snowflake.com/en/sql-reference/constructs/qualify.html#qualify',
 'https://docs.snowflake.com/en/sql-reference/constructs/top_n.html',
 'https://docs.snowflake.com/en/user-guide/access-history.html#write',
 'https://docs.snowflake.com/en/user-guide/ui-snowsight-query.html#using-filters',
 'https://docs.snowflake.com/en/sql-reference/functions/avg.html',
 'https://docs.snowflake.com/en/user-guide/warehouses-considerations.html#how-does-warehouse-caching-impact-queries',
 'https://docs.snowflake.com/en/user-guide/ui-snowsight-visualizations.html#using-charts',
 'https://docs.snowflake.com/en/developer-guide/snowflake-scripting/exceptions.html#raising-a-declared-exception',
 'https://docs.snowflake.com/en/user-guide/data-load-transform.html',
 'https://docs.snowflake.com/en/user-guide-data-load.html#loading-data-into-snowflake',
 'https://docs.snowflake.com/en/sql-reference/constructs/join-lateral.html',
 'https://docs.snowflake.com/en/sql-reference/functions/regr_slope.html',
 'https://docs.snowflake.com/en/sql-reference/functions/parse_json.html',
 'https://docs.snowflake.com/en/user-guide/tables-temp-transient.html',
 'https://docs.snowflake.com/en/user-guide/querying-metadata.html',
 'https://docs.snowflake.com/en/sql-reference/functions-analytic.html',
 'https://docs.snowflake.com/en/sql-reference/functions/copy_history.html',
 'https://docs.snowflake.com/en/sql-reference/stored-procedures-overview.html',
 'https://other-docs.snowflake.com/en/marketplace/consumer.html',
 'https://docs.snowflake.com/en/user-guide/unstructured-intro.html',
 'https://docs.snowflake.com/en/sql-reference/functions/object_agg.html',
 'https://docs.snowflake.com/en/sql-reference/constraints-alter.html',
 'https://docs.snowflake.com/en/user-guide/security-row-using.html#step-3-create-a-row-access-policy',
 'https://docs.snowflake.com/en/sql-reference/functions/flatten.html',
 'https://community.snowflake.com/s/article/NULL-handling-in-Snowflake',
 'https://docs.snowflake.com/en/sql-reference/functions/generator.html',
 'https://docs.snowflake.com/en/user-guide/data-load-web-ui.html',
 'https://docs.snowflake.com/en/sql-reference/functions/dense_rank.html',
 'https://docs.snowflake.com/en/sql-reference/functions/datediff.html#datediff',
 'https://docs.snowflake.com/en/sql-reference/functions/trim.html',
 'https://docs.snowflake.com/en/sql-reference/constraints-overview.html#supported-constraint-types',
 'https://docs.snowflake.com/en/user-guide/ui-snowsight-dashboards.html#sharing-dashboards',
 'https://docs.snowflake.com/en/sql-reference/functions/infer_schema.html',
 'https://docs.snowflake.com/en/sql-reference/account-usage.html',
 'https://docs.snowflake.com/en/sql-reference/constraints.html',
 'https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#copy-options-copyoptions',
 'https://docs.snowflake.com/en/user-guide/querying-persisted-results.html',
 'https://docs.snowflake.com/en/sql-reference/functions/regr_intercept.html',
 'https://docs.snowflake.com/en/sql-reference/functions/stddev_samp.html',
 'https://docs.snowflake.com/en/user-guide/ui-snowsight-visualizations.html',
 'https://docs.snowflake.com/en/sql-reference/functions/corr.html',
 'https://docs.snowflake.com/en/sql-reference/functions/regexp_like.html#examples',
 'https://docs.snowflake.com/en/sql-reference/functions/rank.html',
 'https://docs.snowflake.com/en/sql-reference/functions/count.html#usage-notes',
 'https://docs.snowflake.com/en/user-guide/querying-subqueries.html#correlated-vs-uncorrelated-subqueries',
 'https://docs.snowflake.com/en/sql-reference/functions/lag.html',
 'https://docs.snowflake.com/en/user-guide/querying-joins.html#natural-join',
 'https://docs.snowflake.com/en/user-guide/data-load-bulk.html',
 'https://www.snowflake.com/wp-content/uploads/2017/08/Snowflake-How-to-Analyze-JSON-with-SQL.pdf',
 'https://docs.snowflake.com/en/sql-reference/functions/seq1.html',
 'https://docs.snowflake.com/en/user-guide/object-dependencies.html#gdpr-find-the-data-source-for-a-given-view',
 'https://docs.snowflake.com/en/sql-reference/functions/hll.html',
 'https://docs.snowflake.com/en/sql-reference/data-type-conversion.html#usage-notes',
 'https://docs.snowflake.com/en/sql-reference/functions/split_to_table.html',
 'https://docs.snowflake.com/en/user-guide/querying-semistructured.html']

# Domain Lists
d1 = ["https://community.snowflake.com/s/article/NULL-handling-in-Snowflake",
     "https://docs.snowflake.com/en/user-guide/access-history.html#write",
     "https://docs.snowflake.com/en/sql-reference/account-usage.html",
     "https://docs.snowflake.com/en/user-guide/data-load-bulk.html",
     "https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#copy-options-copyoptions",
     "https://docs.snowflake.com/en/sql-reference/functions/copy_history.html",
     "https://docs.snowflake.com/en/sql-reference/sql/create-table.html#create-table-using-template",
     "https://docs.snowflake.com/en/sql-reference/functions/datediff.html#datediff",
     "https://other-docs.snowflake.com/en/marketplace/consumer.html",
     "https://docs.snowflake.com/en/sql-reference/functions/infer_schema.html",
     "https://docs.snowflake.com/en/user-guide/tables-external-intro.html#general-file-sizing-recommendations",
     "https://docs.snowflake.com/en/user-guide/unstructured-intro.html",
     "https://docs.snowflake.com/en/sql-reference/constructs/join-lateral.html",
     "https://docs.snowflake.com/en/user-guide-data-load.html#loading-data-into-snowflake",
     "https://docs.snowflake.com/en/user-guide/data-load-web-ui.html",
     "https://docs.snowflake.com/en/sql-reference/constraints-alter.html",
     "https://docs.snowflake.com/en/user-guide/object-dependencies.html#gdpr-find-the-data-source-for-a-given-view",
     "https://docs.snowflake.com/en/sql-reference/constraints-overview.html#supported-constraint-types",
     "https://docs.snowflake.com/en/user-guide/data-load-overview.html#detection-of-column-definitions-in-staged-semi-structured-data-files",
     "https://docs.snowflake.com/en/sql-reference/functions/parse_json.html",
     "https://docs.snowflake.com/en/sql-reference/constructs/pivot.html",
     "https://docs.snowflake.com/en/user-guide/data-load-considerations-prepare.html#file-sizing-best-practices-and-limitations",
     "https://docs.snowflake.com/en/sql-reference/sql/put.html",
     "https://docs.snowflake.com/en/user-guide/ui-snowsight-query.html#automatic-contextual-statistics",
     "https://docs.snowflake.com/en/user-guide/querying-metadata.html",
     "https://docs.snowflake.com/en/sql-reference/constructs/qualify.html#qualify",
     "https://docs.snowflake.com/en/sql-reference/constructs/sample.html",
     "https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html#using-values-in-a-variant",
     "https://docs.snowflake.com/en/sql-reference/constructs/top_n.html",
     "https://docs.snowflake.com/en/sql-reference/functions/to_timestamp.html",
     "https://docs.snowflake.com/en/user-guide/data-load-transform.html",
     "https://docs.snowflake.com/en/user-guide/querying-joins.html#natural-join",
     "https://docs.snowflake.com/en/user-guide/querying-subqueries.html#correlated-vs-uncorrelated-subqueries"]

d2 = ["https://community.snowflake.com/s/article/NULL-handling-in-Snowflake",
     "https://community.snowflake.com/s/article/Performance-impact-from-local-and-remote-disk-spilling",
     "https://www.snowflake.com/wp-content/uploads/2017/08/Snowflake-How-to-Analyze-JSON-with-SQL.pdf",
     "https://docs.snowflake.com/en/user-guide/ui-query-profile.html#queries-too-large-to-fit-in-memory",
     "https://docs.snowflake.com/en/sql-reference/functions/count.html#usage-notes",
     "https://docs.snowflake.com/en/sql-reference/data-type-conversion.html#usage-notes",
     "https://docs.snowflake.com/en/sql-reference/functions/datediff.html",
     "https://docs.snowflake.com/en/sql-reference/functions/flatten.html#output",
     "https://docs.snowflake.com/en/sql-reference/functions/lag.html",
     "https://docs.snowflake.com/en/sql-reference/data-types-numeric.html#float-float4-float8",
     "https://docs.snowflake.com/en/sql-reference/functions/object_agg.html",
     "https://docs.snowflake.com/en/user-guide/querying-semistructured.html",
     "https://docs.snowflake.com/en/sql-reference/functions/regexp_like.html#examples",
     "https://docs.snowflake.com/en/sql-reference/constructs/sample.html",
     "https://docs.snowflake.com/en/sql-reference/functions/split_to_table.html",
     "https://docs.snowflake.com/en/sql-reference/functions/trim.html",
     "https://docs.snowflake.com/en/user-guide/data-time-travel.html#changing-the-data-retention-period-for-an-object",
     "https://docs.snowflake.com/en/user-guide/querying-persisted-results.html",
     "https://docs.snowflake.com/en/user-guide/warehouses-considerations.html#how-does-warehouse-caching-impact-queries",
     "https://docs.snowflake.com/en/sql-reference/functions-analytic.html",
     "https://docs.snowflake.com/en/user-guide/views-secure.html#how-might-data-be-exposed-by-a-non-secure-view",
     "https://docs.snowflake.com/en/user-guide/tables-temp-transient.html"]

d3 = ["https://docs.snowflake.com/en/sql-reference/functions/approx_count_distinct.html",
    "https://docs.snowflake.com/en/sql-reference/functions/avg.html",
    "https://docs.snowflake.com/en/sql-reference/constraints.html",
    "https://docs.snowflake.com/en/sql-reference/functions/dense_rank.html",
    "https://docs.snowflake.com/en/user-guide/querying-approximate-cardinality.html",
    "https://docs.snowflake.com/en/sql-reference/sql/explain.html",
    "https://docs.snowflake.com/en/sql-reference/functions/flatten.html",
    "https://docs.snowflake.com/en/developer-guide/snowflake-scripting/exceptions.html#raising-a-declared-exception",
    "https://docs.snowflake.com/en/sql-reference/functions/hll.html",
    "https://docs.snowflake.com/en/sql-reference/functions/ntile.html",
    "https://docs.snowflake.com/en/sql-reference/stored-procedures-overview.html",
    "https://docs.snowflake.com/en/user-guide/ui-snowsight-query.html#creating-custom-filters",
    "https://docs.snowflake.com/en/sql-reference/functions/rank.html",
    "https://docs.snowflake.com/en/sql-reference/functions/regr_intercept.html",
    "https://docs.snowflake.com/en/sql-reference/functions/regr_slope.html",
    "https://docs.snowflake.com/en/sql-reference/functions/row_number.html",
    "https://docs.snowflake.com/en/sql-reference/functions/sha2.html",
    "https://docs.snowflake.com/en/sql-reference/functions/stddev_samp.html",
    "https://docs.snowflake.com/en/user-guide/ui-snowsight-visualizations.html",
    "https://docs.snowflake.com/en/user-guide/views-materialized.html"]

d4 = ["https://docs.snowflake.com/en/sql-reference/account-usage.html",
     "https://docs.snowflake.com/en/sql-reference/functions/corr.html",
     "https://docs.snowflake.com/en/sql-reference/functions/generator.html",
     "https://docs.snowflake.com/en/user-guide/ui-snowsight-query.html#using-filters",
     "https://docs.snowflake.com/en/sql-reference/functions/row_number.html",
     "https://docs.snowflake.com/en/sql-reference/functions/seq1.html",
     "https://docs.snowflake.com/en/user-guide/security-row-using.html#step-3-create-a-row-access-policy",
     "https://docs.snowflake.com/en/user-guide/ui-snowsight-dashboards.html#sharing-dashboards",
     "https://docs.snowflake.com/en/user-guide/ui-snowsight-visualizations.html#using-charts"]

# Data Analyst Dictionary
dict = {"":"",
        "Data Ingestion and Data Preparation": d1,
        "Data Transformation and Data Modeling": d2,
        "Data Analysis": d3,
        "Data Presentation and Data Visualizations": d4,
}