# List of URLs
links = ["https://quickstarts.snowflake.com/guide/attaining_consumer_insights_with_snowflake_and_microsoft_power_bi/index.html?index=..%2F..index#0",
         "https://resources.snowflake.com/ebooks/cloud-data-science-for-dummies",
         "https://resources.snowflake.com/data-science/optimizing-the-machine-learning-lifecycle-and-mlops",
         "https://resources.snowflake.com/data-science/how-to-accelerate-data-science-with-snowflake-2",
         "https://docs.snowflake.com/en/user-guide-admin-governance.html",
         "https://quickstarts.snowflake.com/guide/automl_with_snowflake_and_h2o/index.html?index=..%2F..index#0",
         "https://community.snowflake.com/s/article/cloning-in-snowflake",
         "https://community.snowflake.com/s/article/Using-Streams-and-Tasks-inside-Snowflake",
         "https://community.snowflake.com/s/article/The-Elephant-in-the-Data-Lake-and-Snowflake",
         "https://resources.snowflake.com/white-paper/processing-modern-data-pipelines",
         "https://www.youtube.com/embed/yQIMmXg7Seg",
         "https://www.youtube.com/embed/5AMf8xLJofs",
         "https://resources.snowflake.com/data-science/tdwi-best-practices-report-unifying-data-management-and-analytics-pipelines",
         "https://resources.snowflake.com/data-science/how-to-use-snowflake-native-connectors-for-machine-learning-2021",
         "https://docs.snowflake.com/en/user-guide-data-load.html#loading-data-into-snowflake",
         "https://docs.snowflake.com/en/user-guide-data-share.html",
         "https://docs.snowflake.com/en/user-guide/object-clone.html",
         "https://docs.snowflake.com/en/user-guide/data-time-travel.html",
         "https://docs.snowflake.com/en/sql-reference/stored-procedures.html",
         "https://docs.snowflake.com/en/user-guide/tables-external.html",
         "https://docs.snowflake.com/en/sql-reference/sql/create-database.html",
         "https://docs.snowflake.com/en/sql-reference/sql/create-clone.html",
         "https://docs.snowflake.com/en/user-guide/database-replication-config.html",
         "https://docs.snowflake.com/en/user-guide/data-availability.html",
         "https://docs.snowflake.com/en/sql-reference/functions/task_history.html",
         "https://docs.snowflake.com/en/user-guide/data-pipelines.html",
         "https://docs.snowflake.com/en/sql-reference/constructs/at-before.html#at-before",
         "https://quickstarts.snowflake.com/guide/getting_started_with_snowpark/index.html?index=..%2F..index#0",
         "https://quickstarts.snowflake.com/guide/data_engineering_with_dbt/index.html?index=..%2F..index#0",
         "https://www.snowflake.com/guides/feature-engineering",
         "https://resources.snowflake.com/webinars-thought-leadership/how-post-holdings-embraces-growth-and-innovation-with-snowflake-for-data-science-2",
         "https://resources.snowflake.com/webinars-thought-leadership/how-to-build-a-foundation-for-data-science-with-snowflake-s-data-cloud",
         "https://bigdatadave.com/2020/09/11/snowflake-hands-on-with-the-snowflake-data-marketplace-wunderman-and-covid-19/",
         "https://www.simonwardjones.co.uk/posts/linear_regression_in_snowflake/",
         "https://www.datarobot.com/blog/datarobot-enables-scalable-feature-engineering-and-inference-leveraging-snowflake-snowpark-java-udfs/",
         "https://towardsdatascience.com/feature-engineering-in-snowflake-1730a1b84e5b",
         "https://medium.com/sqldbm/data-discovery-made-easy-with-snowsight-snowflakes-new-ui-ac1a2e26ce36",
         "https://www.snowflake.com/wp-content/uploads/2021/03/Feature-Discovery-with-Snowflake.pdf",
         "https://www.datarobot.com/blog/datarobot-enables-scalable-feature-engineering-and-inference-leveraging-snowflake-snowpark-java-udfs/",
         "https://docs.snowflake.com/en/user-guide/ui-snowsight.html",
         "https://docs.snowflake.com/en/developer-guide/snowpark/working-with-dataframes.html",
         "https://docs.snowflake.com/en/developer-guide/snowpark/working-with-dataframes.html",
         "https://docs.snowflake.com/en/sql-reference/intro-summary-operators-functions.html",
         "https://docs.snowflake.com/en/sql-reference/functions/regr_intercept.html",
         "https://docs.snowflake.com/en/sql-reference/functions/regr_r2.html",
         "https://docs.snowflake.com/en/sql-reference/functions/approx_count_distinct.html",
         "https://docs.snowflake.com/en/developer-guide/snowpark/index.html",
         "https://docs.snowflake.com/en/developer-guide/snowpark/reference/scala/com/snowflake/snowpark/DataFrame.html",
         "https://docs.snowflake.com/en/sql-reference/functions/width_bucket.html",
         "https://docs.snowflake.com/en/sql-reference/functions/ntile.html",
         "https://docs.snowflake.com/en/sql-reference/functions-aggregation.html#aggregate-functions",
         "https://docs.snowflake.com/en/sql-reference/stored-procedures.html",
         "https://docs.snowflake.com/en/user-guide/python-connector-example.html#avoid-sql-injection-attacks",
         "https://docs.snowflake.com/en/sql-reference/constructs/sample.html",
         "https://docs.snowflake.com/en/user-guide/data-availability.html",
         "https://quickstarts.snowflake.com/guide/data_science_with_dataiku/index.html?index=..%2F..index#0",
         "https://quickstarts.snowflake.com/guide/automl_with_snowflake_and_datarobot/index.html?index=..%2F..index#0",
         "https://quickstarts.snowflake.com/guide/machine_learning_with_saturncloud/index.html?index=..%2F..index#0",
         "https://quickstarts.snowflake.com/guide/time_series_forecasting_zepl/index.html?index=..%2F..index#0",
         "https://towardsdatascience.com/machine-learning-in-snowflake-fdcff3bdc1a7",
         "https://resources.snowflake.com/data-science/building-open-source-data-science-models-on-snowflake",
         "https://docs.snowflake.com/en/user-guide/conns-drivers.html",
         "https://docs.snowflake.com/en/user-guide/python-connector-pandas.html",
         "https://docs.snowflake.com/en/sql-reference/external-functions.html",
         "https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html",
         "https://quickstarts.snowflake.com/guide/recommendation_engine_aws_sagemaker/index.html?index=..%2F..index#0",
         "https://quickstarts.snowflake.com/guide/vhol_snowflake_data_wrangler/index.html?index=..%2F..index#0",
         "https://medium.com/starschema-blog/scalable-machine-learning-in-snowflake-distributed-python-from-snowflake-sql-using-bodo-496e13fa9c3e",
         "https://www.persistent.com/blogs/in-place-machine-learning-in-snowflake/",
         "https://www.h2o.ai/blog/h2o-integrates-with-snowflake-snowpark-java-udfs-how-to-better-leverage-the-snowflake-data-marketplace-and-deploy-in-database/",
         "https://blog.dominodatalab.com/accelerating-model-velocity-through-snowflake-java-udf-integration/",
         "https://www.datarobot.com/blog/datarobot-enables-scalable-feature-engineering-and-inference-leveraging-snowflake-snowpark-java-udfs/",
         "https://blog.dataiku.com/snowflake-dataiku-java-udfs-snowpark",
         "https://www.snowflake.com/blog/bringing-extensibility-to-data-pipelines-whats-new-with-snowflake-external-functions/",
         "https://resources.snowflake.com/data-science/master-class-lifecycling-snowpark-and-java-udfs-through-dataops",
         "https://resources.snowflake.com/data-science/external-functions-tutorial-2020",
         "https://docs.snowflake.com/en/sql-reference/sql/create-task.html",
         "https://docs.snowflake.com/en/sql-reference/external-functions.html",
         "https://docs.snowflake.com/en/sql-reference/user-defined-functions.html"]

# Domain Lists
d1 = ["https://quickstarts.snowflake.com/guide/attaining_consumer_insights_with_snowflake_and_microsoft_power_bi/index.html?index=..%2F..index#0",
     "https://resources.snowflake.com/ebooks/cloud-data-science-for-dummies",
     "https://resources.snowflake.com/data-science/optimizing-the-machine-learning-lifecycle-and-mlops",
     "https://resources.snowflake.com/data-science/how-to-accelerate-data-science-with-snowflake-2",
     "https://docs.snowflake.com/en/user-guide-admin-governance.html"]

d2 = ["https://quickstarts.snowflake.com/guide/automl_with_snowflake_and_h2o/index.html?index=..%2F..index#0",
     "https://community.snowflake.com/s/article/cloning-in-snowflake",
     "https://community.snowflake.com/s/article/Using-Streams-and-Tasks-inside-Snowflake",
     "https://community.snowflake.com/s/article/The-Elephant-in-the-Data-Lake-and-Snowflake",
     "https://resources.snowflake.com/white-paper/processing-modern-data-pipelines",
     "https://www.youtube.com/embed/yQIMmXg7Seg",
     "https://www.youtube.com/embed/5AMf8xLJofs",
     "https://resources.snowflake.com/data-science/tdwi-best-practices-report-unifying-data-management-and-analytics-pipelines",
     "https://resources.snowflake.com/data-science/how-to-use-snowflake-native-connectors-for-machine-learning-2021",
     "https://docs.snowflake.com/en/user-guide-data-load.html#loading-data-into-snowflake",
     "https://docs.snowflake.com/en/user-guide-data-share.html",
     "https://docs.snowflake.com/en/user-guide/object-clone.html",
     "https://docs.snowflake.com/en/user-guide/data-time-travel.html",
     "https://docs.snowflake.com/en/sql-reference/stored-procedures.html",
     "https://docs.snowflake.com/en/user-guide/tables-external.html",
     "https://docs.snowflake.com/en/sql-reference/sql/create-database.html",
     "https://docs.snowflake.com/en/sql-reference/sql/create-clone.html",
     "https://docs.snowflake.com/en/user-guide/database-replication-config.html",
     "https://docs.snowflake.com/en/user-guide/data-availability.html",
     "https://docs.snowflake.com/en/sql-reference/functions/task_history.html",
     "https://docs.snowflake.com/en/user-guide/data-pipelines.html"
     "https://docs.snowflake.com/en/sql-reference/constructs/at-before.html#at-before"]

d3 = ["https://quickstarts.snowflake.com/guide/getting_started_with_snowpark/index.html?index=..%2F..index#0",
     "https://quickstarts.snowflake.com/guide/data_engineering_with_dbt/index.html?index=..%2F..index#0",
     "https://www.snowflake.com/guides/feature-engineering",
     "https://resources.snowflake.com/webinars-thought-leadership/how-post-holdings-embraces-growth-and-innovation-with-snowflake-for-data-science-2",
     "https://resources.snowflake.com/webinars-thought-leadership/how-to-build-a-foundation-for-data-science-with-snowflake-s-data-cloud",
     "https://bigdatadave.com/2020/09/11/snowflake-hands-on-with-the-snowflake-data-marketplace-wunderman-and-covid-19/",
     "https://www.simonwardjones.co.uk/posts/linear_regression_in_snowflake/",
     "https://www.datarobot.com/blog/datarobot-enables-scalable-feature-engineering-and-inference-leveraging-snowflake-snowpark-java-udfs/",
     "https://towardsdatascience.com/feature-engineering-in-snowflake-1730a1b84e5b",
     "https://medium.com/sqldbm/data-discovery-made-easy-with-snowsight-snowflakes-new-ui-ac1a2e26ce36",
     "https://www.snowflake.com/wp-content/uploads/2021/03/Feature-Discovery-with-Snowflake.pdf",
     "https://www.datarobot.com/blog/datarobot-enables-scalable-feature-engineering-and-inference-leveraging-snowflake-snowpark-java-udfs/",
     "https://docs.snowflake.com/en/user-guide/ui-snowsight.html",
     "https://docs.snowflake.com/en/developer-guide/snowpark/working-with-dataframes.html",
     "https://docs.snowflake.com/en/sql-reference/intro-summary-operators-functions.html",
     "https://docs.snowflake.com/en/sql-reference/functions/regr_slope.html",
     "https://docs.snowflake.com/en/sql-reference/functions/regr_intercept.html",
     "https://docs.snowflake.com/en/sql-reference/functions/regr_r2.html",
     "https://docs.snowflake.com/en/sql-reference/functions/approx_count_distinct.html",
     "https://docs.snowflake.com/en/developer-guide/snowpark/index.html",
     "https://docs.snowflake.com/en/developer-guide/snowpark/reference/scala/com/snowflake/snowpark/DataFrame.html",
     "https://docs.snowflake.com/en/sql-reference/functions/width_bucket.html",
     "https://docs.snowflake.com/en/sql-reference/functions/ntile.html",
     "https://docs.snowflake.com/en/sql-reference/functions-aggregation.html#aggregate-functions",
     "https://docs.snowflake.com/en/sql-reference/stored-procedures.html",
     "https://docs.snowflake.com/en/user-guide/python-connector-example.html#avoid-sql-injection-attacks",
     "https://docs.snowflake.com/en/sql-reference/constructs/sample.html",
     "https://docs.snowflake.com/en/user-guide/data-availability.html"]

d4 = ["https://quickstarts.snowflake.com/guide/data_science_with_dataiku/index.html?index=..%2F..index#0", 
     "https://quickstarts.snowflake.com/guide/automl_with_snowflake_and_datarobot/index.html?index=..%2F..index#0",
     "https://quickstarts.snowflake.com/guide/machine_learning_with_saturncloud/index.html?index=..%2F..index#0",
     "https://quickstarts.snowflake.com/guide/time_series_forecasting_zepl/index.html?index=..%2F..index#0",
     "https://towardsdatascience.com/machine-learning-in-snowflake-fdcff3bdc1a7",
     "https://resources.snowflake.com/data-science/building-open-source-data-science-models-on-snowflake",
     "https://docs.snowflake.com/en/user-guide/conns-drivers.html",
     "https://docs.snowflake.com/en/user-guide/python-connector-pandas.html",
     "https://docs.snowflake.com/en/sql-reference/external-functions.html",
     "https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html"]

d5 = ["https://quickstarts.snowflake.com/guide/recommendation_engine_aws_sagemaker/index.html?index=..%2F..index#0",
     "https://quickstarts.snowflake.com/guide/vhol_snowflake_data_wrangler/index.html?index=..%2F..index#0",
     "https://medium.com/starschema-blog/scalable-machine-learning-in-snowflake-distributed-python-from-snowflake-sql-using-bodo-496e13fa9c3e",
     "https://www.persistent.com/blogs/in-place-machine-learning-in-snowflake/",
     "https://www.h2o.ai/blog/h2o-integrates-with-snowflake-snowpark-java-udfs-how-to-better-leverage-the-snowflake-data-marketplace-and-deploy-in-database/",
     "https://blog.dominodatalab.com/accelerating-model-velocity-through-snowflake-java-udf-integration/",
     "https://www.datarobot.com/blog/datarobot-enables-scalable-feature-engineering-and-inference-leveraging-snowflake-snowpark-java-udfs/",
     "https://blog.dataiku.com/snowflake-dataiku-java-udfs-snowpark",
     "https://www.snowflake.com/blog/bringing-extensibility-to-data-pipelines-whats-new-with-snowflake-external-functions/",
     "https://resources.snowflake.com/data-science/master-class-lifecycling-snowpark-and-java-udfs-through-dataops",
     "https://resources.snowflake.com/data-science/external-functions-tutorial-2020",
     "https://docs.snowflake.com/en/sql-reference/sql/create-task.html",
     "https://docs.snowflake.com/en/sql-reference/external-functions.html",
     "https://docs.snowflake.com/en/sql-reference/user-defined-functions.html"]

# Data Scientist Dictionary
dict = {"":"",
        "Data Science Concepts": d1,
        "Data Pipelining": d2,
        "Data Preparation and Feature Engineering": d3,
        "Model Development": d4, 
        "Model Deployment": d5}