# List of URLs
links = ["https://resources.snowflake.com/architecture-patterns/snowflake-pattern-security-network-architecture",
        "http://resources.snowflake.com/architecture-patterns/snowflake-pattern-security-authentication",
        "https://resources.snowflake.com/architecture-patterns/snowflake-pattern-security-network-architecture",
        "https://resources.snowflake.com/white-paper/cloud-data-platform-security-how-snowflake-sets-the-standard",
        "https://docs.snowflake.com/en/sql-reference/parameters.html#",
        "https://docs.snowflake.com/en/user-guide/data-time-travel.html#",
        "https://docs.snowflake.com/en/user-guide/replication-failover.html",
        "https://docs.snowflake.com/en/user-guide/data-share-consumers.html#general-limitations-for-shared-databases",
        "https://docs.snowflake.com/en/user-guide/data-sharing-core-tasks-providers.html",
        "https://docs.snowflake.com/en/sql-reference/sql/alter-account.html",
        "https://docs.snowflake.com/en/user-guide/views-secure.html",
        "https://docs.snowflake.com/en/sql-reference/functions/encrypt.html",
        "https://docs.snowflake.com/en/user-guide/object-clone.html",
        "https://docs.snowflake.com/en/sql-reference/sql/create-storage-integration.html",
        "https://docs.snowflake.com/en/user-guide/security-column-intro.html",
        "https://docs.snowflake.com/en/user-guide-admin-security.html",
        "https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#using-sso-with-mfa",
        "https://docs.snowflake.com/en/user-guide/security-access-control-overview.html",
        "https://docs.snowflake.com/en/user-guide/privatelink-azure.html#requirements-and-limitations",
        "https://docs.snowflake.com/en/user-guide/security-mfa.html#connecting-to-snowflake-with-mfa",
        "https://quickstarts.snowflake.com/guide/vhol_data_marketplace_app/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/getting_started_with_time_travel/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/getting_started_with_time_travel/index.html?index=..%2F..index#0",
        "https://developers.snowflake.com/wp-content/uploads/2020/09/SNO-e-Book-20004_SNO-eBook-7-Reference-Architectures-for-Application-Builders-IoT.pdf",
        "https://developers.snowflake.com/wp-content/uploads/2020/09/SNO-eBook-7-Reference-Architectures-for-Application-Builders-AppHealth-SecurityAna.pdf",
        "https://www.snowflake.com/blog/support-multiple-data-modeling-approaches-with-snowflake/",
        "https://www.snowflake.com/blog/data-modeling-in-the-age-of-json-and-schema-on-read/",
        "https://community.snowflake.com/s/article/Different-Types-of-Objects-in-Snowflake",
        "https://community.snowflake.com/s/article/Undrop-object-dropped-or-replaced-multiple-times",
        "https://www.snowflake.com/blog/support-multiple-data-modeling-approaches-with-snowflake/",
        "https://docs.snowflake.com/en/user-guide/data-sharing-core-tasks-providers.html",
        "https://docs.snowflake.com/en/user-guide/tables-external-hive.html",
        "https://docs.snowflake.com/en/user-guide/tables-external-intro.html#partitioned-external-tables",
        "https://docs.snowflake.com/en/user-guide/tables-external.html",
        "https://docs.snowflake.com/en/user-guide/security-access-control-overview.html#securable-objects",
        "https://docs.snowflake.com/en/user-guide/data-time-travel.html#data-retention-period",
        "https://docs.snowflake.com/en/user-guide/database-replication-intro.html",
        "https://docs.snowflake.com/en/sql-reference/sql/create-user.html",
        "https://docs.snowflake.com/en/user-guide/database-replication-failover.html",
        "https://docs.snowflake.com/en/user-guide/object-clone.html",
        "https://quickstarts.snowflake.com/guide/vhol_data_vault/index.html?index=..%2F..index#0",
        "https://quickstarts.snowflake.com/guide/vhol_snowflake_salesforce_tcrm/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/auto_ingest_twitter_data/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/recommendation_engine_aws_sagemaker/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/getting_started_with_snowpipe/index.html?index=..%2F..index#0",
        "https://quickstarts.snowflake.com/guide/data_engineering_with_dbt/index.html?index=..%2F..index#0",
        "https://quickstarts.snowflake.com/guide/getting_started_with_user_defined_functions/index.html?index=..%2F..index#5",
        "https://quickstarts.snowflake.com/guide/getting_started_with_python/index.html?index=..%2F..index#0",
        "https://quickstarts.snowflake.com/guide/getting_started_with_snowsql/index.html?index=..%2F..index#0",
        "https://resources.snowflake.com/white-paper/snowflake-for-data-engineering-easily-ingest-transform-and-deliver-data-for-up-to-the-moment-insight",
        "https://community.snowflake.com/s/article/Using-Streams-and-Tasks-inside-Snowflake",
        "https://www.snowflake.com/blog/masking-semi-structured-data-with-snowflake/",
        "https://www.snowflake.com/blog/easy-continuous-data-pipelines-with-ga-of-streams-and-tasks/",
        "https://docs.snowflake.com/en/user-guide-data-load.html",
        "https://docs.snowflake.com/en/user-guide-data-unload.html",
        "https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#optional-parameters",
        "https://docs.snowflake.com/en/sql-reference/sql/create-stream.html",
        "https://docs.snowflake.com/en/user-guide/data-pipelines.html",
        "https://docs.snowflake.com/en/user-guide/conns-drivers.html#connectors-drivers",
        "https://docs.snowflake.com/en/user-guide/python-connector-example.html#binding-parameters-to-variables-for-batch-inserts",
        "https://docs.snowflake.com/en/sql-reference/functions/system_whitelist_privatelink.html",
        "https://docs.snowflake.com/en/sql-reference/stored-procedures-rights.html",
        "https://docs.snowflake.com/en/user-guide/semistructured-concepts.html",
        "https://docs.snowflake.com/en/user-guide/querying-semistructured.html",
        "https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html",
        "https://guides.snowflake.com/guide/resource_optimization_performance_optimization/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/resource_optimization_billing_metrics/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/resource_optimization_setup/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/resource_optimization_usage_monitoring/index.html?index=..%2F..index#0",
        "https://guides.snowflake.com/guide/vhol_fivetran/index.html?index=..%2F..index#0",
        "https://quickstarts.snowflake.com/guide/data_app/index.html?index=..%2F..index#0",
        "https://quickstarts.snowflake.com/guide/devops_dcm_schemachange_github/index.html?index=..%2F..index#0",
        "https://developers.snowflake.com/wp-content/uploads/2020/09/SNO-eBook-7-Reference-Architectures-for-Application-Builders-Customer360-2.pdf",
        "https://resources.snowflake.com/white-paper/the-rise-of-data-exchanges-frictionless-integration-of-third-party-data",
        "https://docs.snowflake.com/en/user-guide-data-share.html",
        "https://docs.snowflake.com/en/user-guide/tables-clustering-micropartitions.html#clustering-depth-illustrated",
        "https://docs.snowflake.com/en/user-guide/warehouses.html",
        "https://docs.snowflake.com/en/user-guide/tables-clustering-keys.html#reclustering",
        "https://docs.snowflake.com/en/user-guide/data-load-snowpipe-intro.html",
        "https://docs.snowflake.com/en/user-guide/querying-persisted-results.html#retrieval-optimization",
        "https://docs.snowflake.com/en/user-guide/search-optimization-service.html#",
        "https://docs.snowflake.com/en/sql-reference/account-usage.html#differences-between-account-usage-and-information-schema",
        "https://docs.snowflake.com/en/sql-reference/sql/merge.html#nondeterministic-results-for-update-and-delete",
        "https://docs.snowflake.com/en/user-guide/views-materialized.html#how-the-query-optimizer-uses-materialized-views",
        "https://docs.snowflake.com/en/sql-reference/stored-procedures.html"]

# Domain Lists
d1 = ["http://resources.snowflake.com/architecture-patterns/snowflake-pattern-security-access-to-sensitive-objects",
      "http://resources.snowflake.com/architecture-patterns/snowflake-pattern-security-authentication",
      "https://resources.snowflake.com/architecture-patterns/snowflake-pattern-security-network-architecture",
      "https://resources.snowflake.com/white-paper/cloud-data-platform-security-how-snowflake-sets-the-standard",
      "https://docs.snowflake.com/en/sql-reference/parameters.html#",
      "https://docs.snowflake.com/en/user-guide/data-time-travel.html#",
      "https://docs.snowflake.com/en/user-guide/replication-failover.html#replication-and-failover-failback",
      "https://docs.snowflake.com/en/user-guide/data-share-consumers.html#general-limitations-for-shared-databases",
      "https://docs.snowflake.com/en/user-guide/data-sharing-core-tasks-providers.html",
      "https://docs.snowflake.com/en/sql-reference/sql/alter-account.html",
      "https://docs.snowflake.com/en/user-guide/views-secure.html",
      "https://docs.snowflake.com/en/user-guide/security-encryption-manage.html",
      "https://docs.snowflake.com/en/user-guide/object-clone.html",
      "https://docs.snowflake.com/en/sql-reference/sql/create-storage-integration.html",
      "https://docs.snowflake.com/en/user-guide/security-column-intro.html",
      "https://docs.snowflake.com/en/user-guide-admin-security.html",
      "https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#using-sso-with-mfa",
      "https://docs.snowflake.com/en/user-guide/security-access-control-overview.html",
      "https://docs.snowflake.com/en/user-guide/privatelink-azure.html#requirements-and-limitations",
      "https://docs.snowflake.com/en/user-guide/security-mfa.html#connecting-to-snowflake-with-mfa"]

d2 = ["https://quickstarts.snowflake.com/guide/vhol_data_marketplace_app/index.html?index=..%2F..index#0",
      "https://guides.snowflake.com/guide/getting_started_with_time_travel/index.html?index=..%2F..index#0",
      "https://www.snowflake.com/guides/data-modeling",
      "https://developers.snowflake.com/wp-content/uploads/2020/09/SNO-e-Book-20004_SNO-eBook-7-Reference-Architectures-for-Application-Builders-IoT.pdf",
      "https://developers.snowflake.com/wp-content/uploads/2020/09/SNO-eBook-7-Reference-Architectures-for-Application-Builders-AppHealth-SecurityAna.pdf",
      "https://www.snowflake.com/blog/support-multiple-data-modeling-approaches-with-snowflake/",
      "https://www.snowflake.com/blog/data-modeling-in-the-age-of-json-and-schema-on-read/",
      "https://community.snowflake.com/s/article/Different-Types-of-Objects-in-Snowflake",
      "https://community.snowflake.com/s/article/Undrop-object-dropped-or-replaced-multiple-times",
      "https://www.snowflake.com/blog/support-multiple-data-modeling-approaches-with-snowflake/",
      "https://docs.snowflake.com/en/user-guide/data-sharing-core-tasks-providers.html",
      "https://docs.snowflake.com/en/user-guide/tables-external-hive.html",
      "https://docs.snowflake.com/en/user-guide/tables-external-intro.html#partitioned-external-tables",
      "https://docs.snowflake.com/en/user-guide/tables-external.html",
      "https://docs.snowflake.com/en/user-guide/security-access-control-overview.html#securable-objects",
      "https://docs.snowflake.com/en/user-guide/data-time-travel.html#data-retention-period",
      "https://docs.snowflake.com/en/user-guide/database-replication-intro.html",
      "https://docs.snowflake.com/en/sql-reference/sql/create-user.html",
      "https://docs.snowflake.com/en/user-guide/database-replication-failover.html",
      "https://docs.snowflake.com/en/user-guide/object-clone.html"]

d3 = ["https://quickstarts.snowflake.com/guide/vhol_data_vault/index.html?index=..%2F..index#0",
      "https://quickstarts.snowflake.com/guide/vhol_snowflake_salesforce_tcrm/index.html?index=..%2F..index#0",
      "https://guides.snowflake.com/guide/auto_ingest_twitter_data/index.html?index=..%2F..index#0",
      "https://guides.snowflake.com/guide/recommendation_engine_aws_sagemaker/index.html?index=..%2F..index#0",
      "https://guides.snowflake.com/guide/getting_started_with_snowpipe/index.html?index=..%2F..index#0",
      "https://quickstarts.snowflake.com/guide/data_engineering_with_dbt/index.html?index=..%2F..index#0",
      "https://quickstarts.snowflake.com/guide/getting_started_with_user_defined_functions/index.html?index=..%2F..index#5",
      "https://quickstarts.snowflake.com/guide/getting_started_with_python/index.html?index=..%2F..index#0",
      "https://quickstarts.snowflake.com/guide/getting_started_with_snowsql/index.html?index=..%2F..index#0",
      "https://resources.snowflake.com/white-paper/snowflake-for-data-engineering-easily-ingest-transform-and-deliver-data-for-up-to-the-moment-insight",
      "https://resources.snowflake.com/white-paper/snowflake-for-data-engineering-easily-ingest-transform-and-deliver-data-for-up-to-the-moment-insight",
      "https://community.snowflake.com/s/article/Using-Streams-and-Tasks-inside-Snowflake",
      "https://www.snowflake.com/blog/masking-semi-structured-data-with-snowflake/",
      "https://www.snowflake.com/blog/easy-continuous-data-pipelines-with-ga-of-streams-and-tasks/",
      "https://docs.snowflake.com/en/user-guide-data-load.html",
      "https://docs.snowflake.com/en/user-guide-data-unload.html",
      "https://docs.snowflake.com/en/user-guide-data-unload.html",
      "https://docs.snowflake.com/en/sql-reference/sql/create-stream.html",
      "https://docs.snowflake.com/en/user-guide/data-pipelines.html",
      "https://docs.snowflake.com/en/user-guide/conns-drivers.html#connectors-drivers",
      "https://docs.snowflake.com/en/user-guide/python-connector-example.html#binding-parameters-to-variables-for-batch-inserts",
      "https://docs.snowflake.com/en/sql-reference/stored-procedures-rights.html",
      "https://docs.snowflake.com/en/user-guide/semistructured-concepts.html",
      "https://docs.snowflake.com/en/user-guide/querying-semistructured.html",
      "https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html"]

d4 = ["https://guides.snowflake.com/guide/resource_optimization_performance_optimization/index.html?index=..%2F..index#0",
      "https://guides.snowflake.com/guide/resource_optimization_performance_optimization/index.html?index=..%2F..index#0",
      "https://guides.snowflake.com/guide/resource_optimization_setup/index.html?index=..%2F..index#0",
      "https://guides.snowflake.com/guide/resource_optimization_usage_monitoring/index.html?index=..%2F..index#0",
      "https://guides.snowflake.com/guide/vhol_fivetran/index.html?index=..%2F..index#0",
      "https://quickstarts.snowflake.com/guide/data_app/index.html?index=..%2F..index#0",
      "https://quickstarts.snowflake.com/guide/devops_dcm_schemachange_github/index.html?index=..%2F..index#0",
      "https://developers.snowflake.com/wp-content/uploads/2020/09/SNO-eBook-7-Reference-Architectures-for-Application-Builders-Customer360-2.pdf",
      "https://developers.snowflake.com/wp-content/uploads/2020/09/SNO-eBook-7-Reference-Architectures-for-Application-Builders-Customer360-2.pdf",
      "https://docs.snowflake.com/en/user-guide-data-share.html",
      "https://docs.snowflake.com/en/user-guide/tables-clustering-micropartitions.html#clustering-depth-illustrated",
      "https://docs.snowflake.com/en/user-guide/warehouses.html",
      "https://docs.snowflake.com/en/user-guide/tables-clustering-keys.html#reclustering",
      "https://docs.snowflake.com/en/user-guide/data-load-snowpipe-intro.html",
      "https://docs.snowflake.com/en/user-guide/querying-persisted-results.html#retrieval-optimization",
      "https://docs.snowflake.com/en/user-guide/search-optimization-service.html#",
      "https://docs.snowflake.com/en/sql-reference/account-usage.html#differences-between-account-usage-and-information-schema",
      "https://docs.snowflake.com/en/sql-reference/sql/merge.html#nondeterministic-results-for-update-and-delete",
      "https://docs.snowflake.com/en/user-guide/views-materialized.html#how-the-query-optimizer-uses-materialized-views",
      "https://docs.snowflake.com/en/sql-reference/stored-procedures.html",]

# Solutions Architect Dictionary
dict = {"": "",
        "Accounts and Security": d1,
        "Snowflake Architecture": d2,
        "Data Engineering": d3,
        "Performance Optimization": d4}